version: '3.4'

services:
  app:
    image: youracrname.azurecr.io/yourapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Yuan123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
